EE_Scripts_es_debug = true;
EE_Scripts_es_weapon = [
    [], //Level 0
    [["arifle_Mk20_plain_F"]], //Level 1
    [], //Level 2
    [["LMG_mas_m72_F"]], //Level 3
    [["srifle_mas_sr25_v"]], //Level 4
    [["arifle_MX_F","arifle_MX_Black_F"],["arifle_MXC_F","arifle_MXC_Black_F"]], //Level 5
    [["srifle_DMR_01_F"]], //Level 6
    [["hgun_P07_F"],["mas_launch_RPG7_F"]], //Level 7
    [["srifle_mas_ebr"]], //Level 8
    [["LMG_Mk200_F"]], //Level 9
    [["arifle_mas_g36c"],["arifle_TRG21_F"],["arifle_TRG20_F"]], //Level 10
    [["rhs_weap_M136"]], //Level 11
    [["arifle_mas_m70"],["rhs_weap_M136_hedp"]], //Level 12
    [["arifle_MXM_F","arifle_MXM_Black_F"],["rhs_weap_M136_hp"]], //Level 13
    [["arifle_Katiba_C_F"],["arifle_Katiba_F"],["hgun_mas_grach_F"]], //Level 14
    [["arifle_Mk20_GL_plain_F"],["arifle_mas_m27m","arifle_mas_m27m_d","arifle_mas_m27m_v"]], //Level 15
    [["srifle_mas_hk417","srifle_mas_hk417_d","srifle_mas_hk417_v"]], //Level 16
    [["arifle_MX_GL_F","arifle_MX_GL_Black_F"],["rhs_weap_m16a4_carryhandle","rhs_weap_m16a4_carryhandle_grip","rhs_weap_m16a4_carryhandle_M203"]], //Level 17
    [["arifle_SDAR_F"],["mas_launch_LAW_F"]], //Level 18
    [["LMG_mas_M249_F","LMG_mas_M249_F_d","LMG_mas_M249_F_v"]], //Level 19
    [["rhs_weap_m4a1_carryhandle","arifle_mas_m4_d","arifle_mas_m4_v"],["rhs_weap_m4a1_carryhandle_grip2","rhs_weap_m4a1_carryhandle_grip","arifle_mas_m4c_d","arifle_mas_m4c_v"]], //Level 20
    [["srifle_mas_m91"]], //Level 21
    [["arifle_Katiba_GL_F"],["mas_launch_maaws_F"]], //Level 22
    [["arifle_TRG21_GL_F"],["hgun_Pistol_heavy_01_F"]], //Level 23
    [["srifle_mas_sr25","srifle_mas_sr25_d","srifle_mas_sr25_v"]], //Level 24
    [["arifle_mas_hk416","arifle_mas_hk416_d","arifle_mas_hk416_v"],["arifle_mas_hk416c","arifle_mas_hk416c_v","arifle_mas_hk416c_d"]], //Level 25
    [["LMG_mas_pkm_F","LMG_mas_pech_F"]], //Level 26
    [["arifle_mas_m70_gl"],["rhs_weap_smaw_green"]], //Level 27
    [["rhs_weap_XM2010","rhs_weap_XM2010_wd","rhs_weap_XM2010_d","rhs_weap_XM2010_sa"]], //Level 28
    [["hgun_mas_glocksf_F"]], //Level 29
    [["arifle_mas_mk16"],["arifle_mas_mk16_l"]], //Level 30
    [["MMG_01_hex_F","MMG_01_tan_F"]], //Level 31
    [["rhs_weap_sr25_ec","rhs_weap_sr25"]], //Level 32
    [["rhs_weap_m4a1_carryhandle_m203","rhs_weap_m4_m320","arifle_mas_m4_m203_d","arifle_mas_m4_m203_v"]], //Level 33
    [["hgun_mas_uzi_F"],["launch_B_Titan_F"]], //Level 34
    [["rhs_weap_m16a4_carryhandle","rhs_weap_m16a4_carryhandle_grip","rhs_weap_m16a4_carryhandle_M203"],["LMG_mas_mk48_F","LMG_mas_mk48_F_d","LMG_mas_mk48_F_v"]], //Level 35
    [["srifle_mas_mk17s"],["srifle_mas_m110"]], //Level 36
    [["arifle_mas_hk416_m203c","arifle_mas_hk416_m203c_d","arifle_mas_hk416_m203c_v"]], //Level 37
    [["launch_O_Titan_short_F"]], //Level 38
    [["srifle_DMR_05_blk_F","srifle_DMR_05_hex_F","srifle_DMR_05_tan_f"]], //Level 39
    [["srifle_DMR_03_spotter_F","srifle_DMR_03_tan_F","srifle_DMR_03_woodland_F","srifle_DMR_03_khaki_F"],["rhs_weap_m249_pip_L","rhs_weap_m249_pip_L_vfg"]], //Level 40
    [["srifle_mas_sr25","srifle_mas_sr25_d","srifle_mas_sr25_v","srifle_mas_sr25_v"]], //Level 41
    [["srifle_DMR_02_F","srifle_DMR_02_camo_F","srifle_DMR_02_sniper_F"]], //Level 42
    [["srifle_DMR_03_khaki_F","arifle_mas_mk16_gl"]], //Level 43
    [["LMG_mas_m240_F"],["hgun_Pistol_heavy_02_F"],["rhs_weap_fim92"]], //Level 44
    [["FHQ_arifle_ACR_blk","FHQ_arifle_ACR_snw","FHQ_arifle_ACR_tan","FHQ_arifle_ACR_wdl"]], //Level 45
    [["srifle_DMR_03_spotter_F","srifle_DMR_03_tan_F","srifle_DMR_03_woodland_F","srifle_DMR_03_khaki_F"]], //Level 46
    [["rhs_weap_m16a4_carryhandle_M203"],["rhs_weap_fgm148"]], //Level 47
    [["arifle_mas_akm"],["arifle_mas_akm_gl"]], //Level 48
    [["arifle_mas_m4vlt"],["MMG_02_black_F","MMG_02_camo_F","MMG_02_sand_F"]], //Level 49
    [["srifle_mas_mk17"],["arifle_mas_mk17_gl"],["srifle_GM6_F","srifle_GM6_camo_F"],["hgun_mas_mp7p_F"]] //Level 50
  ];
